// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 4.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// hda_sync //
// -------- //

#define hda_sync_wrap_target 0
#define hda_sync_wrap 6
#define hda_sync_pio_version 0

static const uint16_t hda_sync_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xa042, //  1: nop
    0x6001, //  2: out    pins, 1
    0x20a0, //  3: wait   1 pin, 0
    0xa042, //  4: nop
    0x6001, //  5: out    pins, 1
    0x0000, //  6: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hda_sync_program = {
    .instructions = hda_sync_program_instructions,
    .length = 7,
    .origin = -1,
    .pio_version = hda_sync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hda_sync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hda_sync_wrap_target, offset + hda_sync_wrap);
    return c;
}

static inline void hda_sync_program_init(PIO pio, uint sm, uint offset,
                                        uint clk_pin, uint sync_pin, float clkdiv) {
    pio_sm_config c = hda_sync_program_get_default_config(offset);
    // --- Clock pin setup ---
    sm_config_set_in_pins(&c, clk_pin);                 // clock pin
//    pio_gpio_init(pio, clk_pin);
//    pio_sm_set_consecutive_pindirs(pio, sm, clk_pin, 1, false);
    // --- Data pin setup ---
    sm_config_set_out_pins(&c, sync_pin, 1);               // output pin for data
    pio_gpio_init(pio, sync_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, sync_pin, 1, true);
    // --- Optional: autopull for 16-bit words ---
    sm_config_set_out_shift(&c, true, true, 32);           // shift_right=true, autopull=true, threshold=16
    // --- PIO clock divider ---
    sm_config_set_clkdiv(&c, clkdiv);
    // --- Initialize state machine ---
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, false);
}

#endif

