// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 4.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// hda_clk //
// ------- //

#define hda_clk_wrap_target 0
#define hda_clk_wrap 9
#define hda_clk_pio_version 0

static const uint16_t hda_clk_program_instructions[] = {
            //     .wrap_target
    0xe000, //  0: set    pins, 0
    0xa042, //  1: nop
    0xa042, //  2: nop
    0x6001, //  3: out    pins, 1
    0xa042, //  4: nop
    0xe001, //  5: set    pins, 1
    0xa042, //  6: nop
    0xa042, //  7: nop
    0x6001, //  8: out    pins, 1
    0x0000, //  9: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hda_clk_program = {
    .instructions = hda_clk_program_instructions,
    .length = 10,
    .origin = -1,
    .pio_version = hda_clk_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hda_clk_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hda_clk_wrap_target, offset + hda_clk_wrap);
    return c;
}

static inline void hda_clk_program_init(PIO pio, uint sm, uint offset,
                                        uint clk_pin, uint data_pin, float clkdiv) {
    pio_sm_config c = hda_clk_program_get_default_config(offset);
    // --- Clock pin setup ---
    sm_config_set_set_pins(&c, clk_pin, 1);                 // clock pin
    pio_gpio_init(pio, clk_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, clk_pin, 1, true);
    // --- Data pin setup ---
    sm_config_set_out_pins(&c, data_pin, 1);               // output pin for data
    pio_gpio_init(pio, data_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, data_pin, 1, true);
    // --- Optional: autopull for 16-bit words ---
    sm_config_set_out_shift(&c, true, true, 32);           // shift_right=true, autopull=true, threshold=16
    // --- PIO clock divider ---
    sm_config_set_clkdiv(&c, clkdiv);
    // --- Initialize state machine ---
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, false);
}

#endif

